name: Update docs

on: 
  workflow_dispatch:
  schedule:
    - cron:  '45 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Run Python scripts
      env:
          URL: ${{ secrets.URL }}
      run: |-
        python build_docs.py
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "docs-bot@example.com"
        git config --global user.name "docs-bot"
        git add docs/source/index.md
        git commit -m "Updated docs" || exit 0
        git push
